services:
  client:
    image: node:22-alpine
    container_name: assay-client
    working_dir: /workspace
    environment:
      NODE_ENV: development
      VITE_API_URL: "http://server:${SERVER_PORT:-3000}"

    command: sh -c "
      npm i -g pnpm &&
      pnpm install &&
      pnpm --filter client dev"

    env_file: ".env"

    volumes:
      - ./:/workspace
      - client_node_modules:/workspace/node_modules
      - pnpm_store:/pnpm-store

    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"

    networks:
      - assay

  server:
    image: node:22-alpine
    container_name: assay-server
    working_dir: /workspace
    environment:
      NODE_ENV: development

    command: sh -c "
      npm i -g pnpm &&
      pnpm install &&
      pnpm --filter server dev"

    env_file: ".env"

    volumes:
      - ./:/workspace
      - server_node_modules:/workspace/node_modules
      - pnpm_store:/pnpm-store

    ports:
      - "${SERVER_PORT:-3000}:${SERVER_PORT:-3000}"

    networks:
      - assay

volumes:
  client_node_modules:
  server_node_modules:
  pnpm_store:

networks:
  assay:
    name: assay
